/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab5p2_víctorromero;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author IFRST
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListarPersonaje = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Personajes = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Agregar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Jt_Nombre = new javax.swing.JTextField();
        Poder = new javax.swing.JLabel();
        Poder1 = new javax.swing.JLabel();
        Jt_Poder = new javax.swing.JTextField();
        Poder2 = new javax.swing.JLabel();
        Jt_Debilidad = new javax.swing.JTextField();
        Poder3 = new javax.swing.JLabel();
        Poder4 = new javax.swing.JLabel();
        jft_Fuerza = new javax.swing.JFormattedTextField();
        Poder5 = new javax.swing.JLabel();
        jft_Fisica = new javax.swing.JFormattedTextField();
        Poder6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jft_Mental = new javax.swing.JFormattedTextField();
        Name = new javax.swing.JLabel();
        Poder7 = new javax.swing.JLabel();
        jft_Vida = new javax.swing.JFormattedTextField();
        jB_Agregar1 = new javax.swing.JButton();
        jB_Agregar = new javax.swing.JButton();
        Agregar = new javax.swing.JLabel();
        Batalla = new javax.swing.JLabel();
        MainScree = new javax.swing.JLabel();

        ListarPersonaje.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Marvel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Caprom");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("MK");
        treeNode1.add(treeNode2);
        jt_Personajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_PersonajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Personajes);

        ListarPersonaje.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 340, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        ListarPersonaje.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 320, 360));

        Agregar1.setBackground(new java.awt.Color(255, 0, 0));
        Agregar1.setFont(new java.awt.Font("Impact", 0, 75)); // NOI18N
        Agregar1.setForeground(new java.awt.Color(255, 255, 255));
        Agregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Agregar1.setText("LISTAR PERSONAJES");
        Agregar1.setOpaque(true);
        ListarPersonaje.getContentPane().add(Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5p2_víctorromero/Imagenes/MainScreen.jpg"))); // NOI18N
        ListarPersonaje.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Jt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 670, 30));

        Poder.setBackground(new java.awt.Color(255, 255, 255));
        Poder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder.setForeground(new java.awt.Color(0, 0, 0));
        Poder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder.setText("Nombre");
        Poder.setOpaque(true);
        getContentPane().add(Poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 30));

        Poder1.setBackground(new java.awt.Color(255, 255, 255));
        Poder1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder1.setForeground(new java.awt.Color(0, 0, 0));
        Poder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder1.setText("Poder");
        Poder1.setOpaque(true);
        getContentPane().add(Poder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 30));
        getContentPane().add(Jt_Poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 670, 30));

        Poder2.setBackground(new java.awt.Color(255, 255, 255));
        Poder2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder2.setForeground(new java.awt.Color(0, 0, 0));
        Poder2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder2.setText("Debilidad");
        Poder2.setOpaque(true);
        getContentPane().add(Poder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 110, 30));
        getContentPane().add(Jt_Debilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 670, 30));

        Poder3.setBackground(new java.awt.Color(255, 255, 255));
        Poder3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder3.setForeground(new java.awt.Color(0, 0, 0));
        Poder3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder3.setText("Universo");
        Poder3.setOpaque(true);
        getContentPane().add(Poder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 110, 30));

        Poder4.setBackground(new java.awt.Color(255, 255, 255));
        Poder4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder4.setForeground(new java.awt.Color(0, 0, 0));
        Poder4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder4.setText("Fuerza");
        Poder4.setOpaque(true);
        getContentPane().add(Poder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 140, 30));

        jft_Fuerza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jft_Fuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 140, 30));

        Poder5.setBackground(new java.awt.Color(255, 255, 255));
        Poder5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder5.setForeground(new java.awt.Color(0, 0, 0));
        Poder5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder5.setText("Ag. Fisica");
        Poder5.setOpaque(true);
        getContentPane().add(Poder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 140, 30));

        jft_Fisica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jft_Fisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 140, 30));

        Poder6.setBackground(new java.awt.Color(255, 255, 255));
        Poder6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder6.setForeground(new java.awt.Color(0, 0, 0));
        Poder6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder6.setText("Ag. Mental");
        Poder6.setOpaque(true);
        getContentPane().add(Poder6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 140, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Caprom", "MK" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 670, 30));

        jft_Mental.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jft_Mental, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 140, 30));

        Name.setBackground(new java.awt.Color(0, 0, 0));
        Name.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Name.setForeground(new java.awt.Color(0, 0, 0));
        Name.setText("Víctor Romero - 12211079");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 30));

        Poder7.setBackground(new java.awt.Color(255, 255, 255));
        Poder7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Poder7.setForeground(new java.awt.Color(0, 0, 0));
        Poder7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poder7.setText("Vida");
        Poder7.setOpaque(true);
        getContentPane().add(Poder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 140, 30));

        jft_Vida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jft_Vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 140, 30));

        jB_Agregar1.setBackground(new java.awt.Color(255, 0, 0));
        jB_Agregar1.setFont(new java.awt.Font("Impact", 0, 55)); // NOI18N
        jB_Agregar1.setForeground(new java.awt.Color(255, 255, 255));
        jB_Agregar1.setText("LISTAR");
        jB_Agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Agregar1MouseClicked(evt);
            }
        });
        jB_Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Agregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 240, 70));

        jB_Agregar.setBackground(new java.awt.Color(255, 0, 0));
        jB_Agregar.setFont(new java.awt.Font("Impact", 0, 55)); // NOI18N
        jB_Agregar.setForeground(new java.awt.Color(255, 255, 255));
        jB_Agregar.setText("AGREGAR ");
        jB_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_AgregarMouseClicked(evt);
            }
        });
        jB_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 240, 70));

        Agregar.setBackground(new java.awt.Color(255, 0, 0));
        Agregar.setFont(new java.awt.Font("Impact", 0, 75)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Agregar.setText("AGREGAR PERSONAJE");
        Agregar.setOpaque(true);
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 80));

        Batalla.setBackground(new java.awt.Color(255, 0, 0));
        Batalla.setFont(new java.awt.Font("Impact", 0, 60)); // NOI18N
        Batalla.setForeground(new java.awt.Color(255, 255, 255));
        Batalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Batalla.setText("BATALLA");
        Batalla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Batalla.setOpaque(true);
        Batalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BatallaMouseClicked(evt);
            }
        });
        getContentPane().add(Batalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 240, 70));

        MainScree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5p2_víctorromero/Imagenes/MainScreen.jpg"))); // NOI18N
        MainScree.setText("jLabel1");
        getContentPane().add(MainScree, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 795, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BatallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatallaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BatallaMouseClicked

    private void jB_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_AgregarActionPerformed

    private void jB_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_AgregarMouseClicked
        int index = 0;
        index = jComboBox1.getSelectedIndex();
        personajes.add(
                new Personajes(Jt_Nombre.getText(),
                        Jt_Poder.getText(),
                        Jt_Debilidad.getText(),
                        jComboBox1.getItemAt(index),
                        Integer.parseInt(jft_Fuerza.getText()),
                        Integer.parseInt(jft_Fisica.getText()),
                        Integer.parseInt(jft_Mental.getText()),
                        Integer.parseInt(jft_Vida.getText()))
        );
        Jt_Nombre.setText("");
        Jt_Poder.setText("");
        Jt_Debilidad.setText("");
        jft_Fuerza.setText("");
        jft_Fisica.setText("");
        jft_Mental.setText("");
        jft_Vida.setText("");

        System.out.println(personajes);
    }//GEN-LAST:event_jB_AgregarMouseClicked

    private void jB_Agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Agregar1MouseClicked
        MainScree.setVisible(false);
        ListarPersonaje.setVisible(true);
    }//GEN-LAST:event_jB_Agregar1MouseClicked

    private void jB_Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Agregar1ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();

        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();

        DefaultMutableTreeNode nodo_personaje;

        for (Personajes personaje : personajes) {
            switch (personaje.getUniverso()) {
                case "DC": {
                    nodo_personaje = new DefaultMutableTreeNode(personaje.getNombre());
                    ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(nodo_personaje);
                }
                break;

                case "Marvel": {
                    nodo_personaje = new DefaultMutableTreeNode(personaje.getNombre());
                    ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(nodo_personaje);
                }
                break;

                case "MK": {
                    nodo_personaje = new DefaultMutableTreeNode(personaje.getNombre());
                    ((DefaultMutableTreeNode) raiz.getChildAt(3)).add(nodo_personaje);
                }
                break;

                case "Capcom": {
                    nodo_personaje = new DefaultMutableTreeNode(personaje.getNombre());
                    ((DefaultMutableTreeNode) raiz.getChildAt(2)).add(nodo_personaje);
                }
                break;
            }

            m.reload();

            setVisible(false);
            ListarPersonaje.setVisible(true);
            ListarPersonaje.pack();
            ListarPersonaje.setLocationRelativeTo(this);

    }//GEN-LAST:event_jB_Agregar1ActionPerformed
    }
    private void jt_PersonajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_PersonajesMouseClicked
        String n="";
        try{
            n = jt_Personajes.getSelectionPath().getLastPathComponent().toString();
        }catch(Exception e){
            System.out.println("");
        }
        
      // String x = n.toString();
        System.out.println(n);
        String nuilaGay="";
        //esta line la puso Eduardo, no te enojes <3
        for (int i = 0; i < personajes.size(); i++) {
            if(personajes.get(i).getNombre().equals(n)){
                nuilaGay=personajes.get(i).toString();
            }
        }
        
        if (n.toString() != "DC" && n.toString() != "Marvel" && n.toString() != "Capcom" && n.toString() != "MK") {
        //   Personajes p = (Personajes) n;
            jTextArea1.append(nuilaGay);
//            jTextArea1.append(p.getPoder());
//            jTextArea1.append(p.getDebilidad());
//            jTextArea1.append(p.getUniverso());
//            jTextArea1.append(p.getFuerza() + "");
//            jTextArea1.append(p.getFuerza() + "");
//            jTextArea1.append(p.getFuerza() + "");
            jTextArea1.append("____________________________\n"
                    + "");
            
        }
    }//GEN-LAST:event_jt_PersonajesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    ArrayList<Personajes> personajes = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel Agregar1;
    private javax.swing.JLabel Batalla;
    private javax.swing.JTextField Jt_Debilidad;
    private javax.swing.JTextField Jt_Nombre;
    private javax.swing.JTextField Jt_Poder;
    private javax.swing.JFrame ListarPersonaje;
    private javax.swing.JLabel MainScree;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Poder;
    private javax.swing.JLabel Poder1;
    private javax.swing.JLabel Poder2;
    private javax.swing.JLabel Poder3;
    private javax.swing.JLabel Poder4;
    private javax.swing.JLabel Poder5;
    private javax.swing.JLabel Poder6;
    private javax.swing.JLabel Poder7;
    private javax.swing.JButton jB_Agregar;
    private javax.swing.JButton jB_Agregar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JFormattedTextField jft_Fisica;
    private javax.swing.JFormattedTextField jft_Fuerza;
    private javax.swing.JFormattedTextField jft_Mental;
    private javax.swing.JFormattedTextField jft_Vida;
    private javax.swing.JTree jt_Personajes;
    // End of variables declaration//GEN-END:variables
}
